// Declares static image imports (`import logo from './public/logos/amazon.png'`)
// as modules resolving to StaticImageData.
//
// `next-env.d.ts` carries the same reference, but it is gitignored and only
// regenerated by `next build` — so a standalone `tsc --noEmit` in CI, running
// before the build, would not see it. This file is committed, so typechecking
// works without a build step first.
/// <reference types="next/image-types/global" />
